<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index()
    {
        //fetch 16 products per page from the database
        $products = Product::paginate(16);
        $totalProducts = Product::count();

        //return products as JSON
        return response()->json([
            'products' => $products,
            'total' => $totalProducts
        ]);
    }

    public function show($slug)
    {
        // Fetch a single product by slug
        $product = Product::where('slug', $slug)->first();

        if (!$product) {
            // Return a 404 response if the product is not found
            return response()->json(['error' => 'Product not found'], 404);
        }

        // Return the product as JSON
        return response()->json($product);
    }

    public function store(Request $request)
    {
        // Validate the incoming request data
        $validatedData = $request->validate([
            'name' => 'required|string|max:255',
            'price' => 'required|numeric',
            'image_url' => 'required|string',
            'vendor' => 'required|string|max:255',
            'rating' => 'nullable|integer',
            'reviews' => 'nullable|integer',
            'description' => 'nullable|string'
        ]);

        // Create a new product using the validated data
        $product = Product::create($validatedData);

        // The slug will automatically be generated by the Sluggable trait

        // Return the created product as JSON
        return response()->json($product, 201); // 201 status code means 'Created'
    }
}
