<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            [
                'name' => 'Handcrafted Maasai Earrings',
                'slug' => 'handcrafted-maasai-earrings',
                'description' => 'Vibrant Beaded Design, Traditional African Patterns',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726660393/IMG_2056_edptam.jpg',
                'price' => 11.95,
                'vendor_name' => 'Maasai Crafts',
                'vendor_email' => 'info@maasaicrafts.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 0,
                'dimensions' => 'N/A',
                'weight' => 0.02,
                'material' => 'Beads',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Handcrafted Brass Necklace',
                'slug' => 'handcrafted-brass-necklace',
                'description' => 'Adjustable Length, Durable and Stylish, Gold Finish',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1725290282/IMG_1841_pxxkgj.jpg',
                'price' => 9.99,
                'vendor_name' => 'Cultured Brass',
                'vendor_email' => 'info@culturedbrass.com',
                'vendor_location' => 'Mombasa, Kenya',
                'stock' => 10,
                'dimensions' => '50cm x 1cm',
                'weight' => 0.1,
                'material' => 'Brass',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Handcrafted Beaded Dining Table Mats',
                'slug' => 'handcrafted-beaded-dining-table-mats',
                'description' => 'Vibrant Colors and Patterns, Durable and Easy to Clean',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726658286/IMG_1875_1_pakgbb.jpg',
                'price' => 120.00,
                'vendor_name' => 'Beads by Judy',
                'vendor_email' => 'info@beadsbyjudy.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 10,
                'dimensions' => '40cm x 30cm',
                'weight' => 0.3,
                'material' => 'Cotton and Beads',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Wall Art',
                'slug' => 'wall-art',
                'description' => 'Unique African-Inspired Design, High-Quality Materials',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726660769/IMG_1874_qpp9p1.jpg',
                'price' => 60.00,
                'vendor_name' => 'Shona Artists',
                'vendor_email' => 'info@shonaartists.com',
                'vendor_location' => 'Harare, Zimbabwe',
                'stock' => 10,
                'dimensions' => '60cm x 90cm',
                'weight' => 1.5,
                'material' => 'Wood and Paint',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Handwoven African Basket',
                'slug' => 'handwoven-african-basket',
                'description' => 'Intricate Traditional Patterns, Ideal for Decorative or Functional Use',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726660981/IMG_1890_wqzy3f.jpg',
                'price' => 25.50,
                'vendor_name' => 'Kenya Weavers',
                'vendor_email' => 'info@kenyaweavers.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 10,
                'dimensions' => '30cm diameter',
                'weight' => 0.4,
                'material' => 'Natural Fibers',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'African Sculpture',
                'slug' => 'african-sculpture',
                'description' => 'Unique Traditional Design, Made from High-Quality Materials',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661077/IMG_1900_ejhcbh.jpg',
                'price' => 80.00,
                'vendor_name' => 'Zanzibar Artists',
                'vendor_email' => 'info@zanzibarartists.com',
                'vendor_location' => 'Zanzibar, Tanzania',
                'stock' => 5,
                'dimensions' => '45cm x 25cm',
                'weight' => 2.0,
                'material' => 'Wood',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Handmade Soap',
                'slug' => 'handmade-soap',
                'description' => 'Natural Ingredients, Eco-Friendly, Moisturizing Formula',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661271/IMG_1910_fiv2n4.jpg',
                'price' => 5.00,
                'vendor_name' => 'Organic Soaps Co.',
                'vendor_email' => 'info@organicsoaps.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 20,
                'dimensions' => '10cm x 5cm',
                'weight' => 0.1,
                'material' => 'Natural Ingredients',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Leather Handbag',
                'slug' => 'leather-handbag',
                'description' => 'Stylish and Functional, Durable Leather, Perfect for Daily Use',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661350/IMG_1912_zihxkm.jpg',
                'price' => 150.00,
                'vendor_name' => 'Leather Works',
                'vendor_email' => 'info@leatherworks.com',
                'vendor_location' => 'Kampala, Uganda',
                'stock' => 5,
                'dimensions' => '30cm x 25cm x 10cm',
                'weight' => 0.8,
                'material' => 'Leather',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Decorative Throw Pillows',
                'slug' => 'decorative-throw-pillows',
                'description' => 'Bright Colors, Comfortable, Handcrafted with Unique Designs',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661463/IMG_1920_zld9xo.jpg',
                'price' => 30.00,
                'vendor_name' => 'Home Decor Co.',
                'vendor_email' => 'info@homedecor.com',
                'vendor_location' => 'Lagos, Nigeria',
                'stock' => 15,
                'dimensions' => '40cm x 40cm',
                'weight' => 0.5,
                'material' => 'Cotton',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Handmade Ceramic Mug',
                'slug' => 'handmade-ceramic-mug',
                'description' => 'Unique Designs, Microwave and Dishwasher Safe',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661554/IMG_1925_knvf5g.jpg',
                'price' => 15.00,
                'vendor_name' => 'Pottery Co.',
                'vendor_email' => 'info@potteryco.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 30,
                'dimensions' => '10cm x 8cm',
                'weight' => 0.25,
                'material' => 'Ceramic',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Handcrafted Wooden Coasters',
                'slug' => 'handcrafted-wooden-coasters',
                'description' => 'Set of 4, Unique Designs, Eco-Friendly',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661639/IMG_1930_splh9n.jpg',
                'price' => 20.00,
                'vendor_name' => 'Eco Craft',
                'vendor_email' => 'info@ecocraft.com',
                'vendor_location' => 'Kampala, Uganda',
                'stock' => 25,
                'dimensions' => '10cm x 10cm',
                'weight' => 0.3,
                'material' => 'Wood',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Traditional Beaded Necklace',
                'slug' => 'traditional-beaded-necklace',
                'description' => 'Handmade, Unique Patterns, Perfect Gift',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661713/IMG_1933_mhx0g2.jpg',
                'price' => 40.00,
                'vendor_name' => 'Artisan Jewelry',
                'vendor_email' => 'info@artisanjewelry.com',
                'vendor_location' => 'Lagos, Nigeria',
                'stock' => 12,
                'dimensions' => '20cm',
                'weight' => 0.1,
                'material' => 'Glass Beads',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Canvas Art Print',
                'slug' => 'canvas-art-print',
                'description' => 'Beautiful Artwork, Ready to Hang, High-Quality Print',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661785/IMG_1936_zit9gv.jpg',
                'price' => 70.00,
                'vendor_name' => 'Art & Co.',
                'vendor_email' => 'info@artandco.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 8,
                'dimensions' => '60cm x 40cm',
                'weight' => 1.0,
                'material' => 'Canvas',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Knitted Blanket',
                'slug' => 'knitted-blanket',
                'description' => 'Warm and Cozy, Perfect for Cold Evenings, Handmade',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661861/IMG_1941_wt16f6.jpg',
                'price' => 100.00,
                'vendor_name' => 'Cozy Knits',
                'vendor_email' => 'info@cozyknits.com',
                'vendor_location' => 'Kampala, Uganda',
                'stock' => 5,
                'dimensions' => '120cm x 150cm',
                'weight' => 1.5,
                'material' => 'Wool',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Essential Oil Set',
                'slug' => 'essential-oil-set',
                'description' => 'Pure Oils, Aromatherapy, Relaxing Scents',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726661957/IMG_1944_lnbbkn.jpg',
                'price' => 35.00,
                'vendor_name' => 'Wellness Co.',
                'vendor_email' => 'info@wellnessco.com',
                'vendor_location' => 'Lagos, Nigeria',
                'stock' => 25,
                'dimensions' => '5cm x 5cm',
                'weight' => 0.2,
                'material' => 'Natural Ingredients',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Personalized Tote Bag',
                'slug' => 'personalized-tote-bag',
                'description' => 'Customizable, Durable, Perfect for Shopping',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662038/IMG_1947_yo5vho.jpg',
                'price' => 25.00,
                'vendor_name' => 'Bag Co.',
                'vendor_email' => 'info@bagco.com',
                'vendor_location' => 'Kampala, Uganda',
                'stock' => 15,
                'dimensions' => '40cm x 35cm',
                'weight' => 0.4,
                'material' => 'Canvas',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Ceramic Coffee Mug',
                'slug' => 'ceramic-coffee-mug',
                'description' => 'Handcrafted, Microwave Safe, Stylish Design',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662100/IMG_1950_qx9hwi.jpg',
                'price' => 15.00,
                'vendor_name' => 'Mug Masters',
                'vendor_email' => 'info@mugmasters.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 30,
                'dimensions' => '12cm x 10cm',
                'weight' => 0.5,
                'material' => 'Ceramic',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Eco-Friendly Notebook',
                'slug' => 'eco-friendly-notebook',
                'description' => 'Recycled Paper, Perfect for Notes, Sustainable',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662150/IMG_1953_sbgxra.jpg',
                'price' => 10.00,
                'vendor_name' => 'Eco Goods',
                'vendor_email' => 'info@ecogoods.com',
                'vendor_location' => 'Kampala, Uganda',
                'stock' => 50,
                'dimensions' => '15cm x 21cm',
                'weight' => 0.3,
                'material' => 'Recycled Paper',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Wireless Phone Charger',
                'slug' => 'wireless-phone-charger',
                'description' => 'Fast Charging, Sleek Design, Compatible with All Devices',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662200/IMG_1956_t9ge8s.jpg',
                'price' => 25.00,
                'vendor_name' => 'Tech World',
                'vendor_email' => 'info@techworld.com',
                'vendor_location' => 'Lagos, Nigeria',
                'stock' => 20,
                'dimensions' => '10cm x 10cm',
                'weight' => 0.3,
                'material' => 'Plastic',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Vintage Style Wall Clock',
                'slug' => 'vintage-style-wall-clock',
                'description' => 'Rustic Design, Silent Mechanism, Easy to Read',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662250/IMG_1959_bq5emg.jpg',
                'price' => 50.00,
                'vendor_name' => 'Home Decor',
                'vendor_email' => 'info@homedecor.com',
                'vendor_location' => 'Kampala, Uganda',
                'stock' => 10,
                'dimensions' => '30cm',
                'weight' => 0.8,
                'material' => 'Wood',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Travel Backpack',
                'slug' => 'travel-backpack',
                'description' => 'Durable, Water-Resistant, Multi-Functional',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662300/IMG_1962_wgw1yk.jpg',
                'price' => 70.00,
                'vendor_name' => 'Outdoor Gear',
                'vendor_email' => 'info@outdoorgear.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 15,
                'dimensions' => '40cm x 30cm',
                'weight' => 1.0,
                'material' => 'Nylon',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Bluetooth Wireless Earbuds',
                'slug' => 'bluetooth-wireless-earbuds',
                'description' => 'High Sound Quality, Noise Cancelling, Long Battery Life',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662350/IMG_1965_vfep4n.jpg',
                'price' => 60.00,
                'vendor_name' => 'Audio Tech',
                'vendor_email' => 'info@audiotech.com',
                'vendor_location' => 'Lagos, Nigeria',
                'stock' => 25,
                'dimensions' => 'Small',
                'weight' => 0.05,
                'material' => 'Plastic',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Yoga Mat',
                'slug' => 'yoga-mat',
                'description' => 'Non-Slip, Eco-Friendly, Thick Padding',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662400/IMG_1968_zlrdu3.jpg',
                'price' => 35.00,
                'vendor_name' => 'Fitness Gear',
                'vendor_email' => 'info@fitnessgear.com',
                'vendor_location' => 'Kampala, Uganda',
                'stock' => 40,
                'dimensions' => '183cm x 61cm',
                'weight' => 1.2,
                'material' => 'PVC',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Portable Blender',
                'slug' => 'portable-blender',
                'description' => 'Rechargeable, Smoothies on the Go, Compact Design',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662450/IMG_1971_yqsakj.jpg',
                'price' => 45.00,
                'vendor_name' => 'Kitchen Essentials',
                'vendor_email' => 'info@kitchenessentials.com',
                'vendor_location' => 'Nairobi, Kenya',
                'stock' => 15,
                'dimensions' => '20cm x 8cm',
                'weight' => 0.6,
                'material' => 'Plastic',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Gourmet Olive Oil',
                'slug' => 'gourmet-olive-oil',
                'description' => 'Extra Virgin, Cold Pressed, Rich Flavor',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662500/IMG_1974_xqz6wo.jpg',
                'price' => 30.00,
                'vendor_name' => 'Gourmet Foods',
                'vendor_email' => 'info@gourmetfoods.com',
                'vendor_location' => 'Lagos, Nigeria',
                'stock' => 20,
                'dimensions' => '500ml',
                'weight' => 0.5,
                'material' => 'Glass Bottle',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
            [
                'name' => 'Fitness Resistance Bands',
                'slug' => 'fitness-resistance-bands',
                'description' => 'Durable, Adjustable, Perfect for Workouts',
                'image_url' => 'https://res.cloudinary.com/kwishi/image/upload/v1726662550/IMG_1977_mgsybd.jpg',
                'price' => 20.00,
                'vendor_name' => 'Fitness Gear',
                'vendor_email' => 'info@fitnessgear.com',
                'vendor_location' => 'Kampala, Uganda',
                'stock' => 30,
                'dimensions' => 'Standard',
                'weight' => 0.4,
                'material' => 'Latex',
                'thumbnails' => [
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723877597/IMG_1868_pz49ft.jpg', 'alt' => 'Front view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723876880/A08FAA78-332F-4BC8-B5B9-91C2AA28B634_pu9wfi.jpg', 'alt' => 'Back view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723451902/62180B51-9E28-438B-9C93-5BD7227193CC_wnlwco.jpg', 'alt' => 'Left view'],
                    ['src' => 'https://res.cloudinary.com/kwishi/image/upload/v1723449027/IMG_1831_cdtsrb.png', 'alt' => 'Right view']
                ],
            ],
        ];

        foreach ($products as $product) {
            Product::firstOrCreate(['slug' => $product['slug']], $product);
        }
    }
}
